# Generated by Django 2.2.6 on 2019-10-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiApimodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'api_apimodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesCaderno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=100)),
                ('tribunal', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField()),
            ],
            options={
                'db_table': 'recortes_caderno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesControle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao_unica', models.CharField(max_length=20)),
                ('recorte', models.TextField()),
                ('data_criacao', models.DateField()),
                ('codigo_diario', models.CharField(max_length=200)),
                ('ids_recortes_filhos', models.TextField()),
                ('fonte', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'recortes_controle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
                ('data_publicacao', models.DateTimeField()),
                ('codigo_diario', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'recortes_diario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesDownloaddiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_diario', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'recortes_downloaddiario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesLinkIgnorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('id_recorte', models.BigIntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=254)),
                ('motivo', models.TextField()),
                ('nome', models.CharField(max_length=200)),
                ('rg', models.CharField(max_length=20)),
                ('data_criacao', models.DateTimeField()),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
                ('remover_completamente', models.BooleanField()),
                ('numeracao_unica', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'recortes_link_ignorado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesLogcommanddownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=200)),
                ('instancia_id', models.CharField(blank=True, max_length=50, null=True)),
                ('log_text', models.TextField()),
                ('finalizado', models.BooleanField()),
                ('data_criacao', models.DateTimeField()),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
                ('tempo_de_execucao', models.DecimalField(decimal_places=4, max_digits=8)),
                ('parametros', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'recortes_logcommanddownload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesNomecaderno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('codigo_caderno', models.CharField(max_length=500)),
                ('data_criacao', models.DateTimeField()),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recortes_nomecaderno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesNomediario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('codigo_diario', models.CharField(max_length=500)),
                ('segmento_judiciario', models.CharField(blank=True, max_length=20, null=True)),
                ('tribunal', models.CharField(blank=True, max_length=50, null=True)),
                ('data_criacao', models.DateTimeField()),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
                ('estados', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'recortes_nomediario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesRecorteStfStj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField()),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
                ('numeracao_unica', models.CharField(blank=True, max_length=20, null=True)),
                ('recorte', models.TextField()),
                ('data_publicacao', models.DateTimeField()),
                ('codigo_diario', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'recortes_recorte_stf_stj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesRecorteTjmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField()),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
                ('numeracao_unica', models.CharField(blank=True, max_length=40, null=True)),
                ('recorte', models.TextField()),
                ('data_publicacao', models.DateTimeField()),
                ('codigo_diario', models.CharField(max_length=200)),
                ('caderno', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'recortes_recorte_tjmt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesRegistrodownloaddiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('data_criacao', models.DateTimeField()),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recortes_registrodownloaddiario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecortesRecorte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
                ('numeracao_unica', models.CharField(max_length=20)),
                ('recorte', models.TextField()),
                ('data_publicacao', models.DateField()),
                ('codigo_diario', models.CharField(max_length=200)),
                ('caderno', models.CharField(blank=True, max_length=200, null=True)),
                ('novo_recorte', models.BooleanField()),
                ('paginas_diario', models.TextField(blank=True, null=True)),
                ('nup_invalido', models.BooleanField(blank=True, null=True)),
                ('nup_invalido_msg', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'recortes_recorte',
            },
        ),
    ]
